{{- if .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devault.fullname" . }}-console
  labels:
    {{- include "devault.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  type: ClusterIP
  selector:
    {{- include "devault.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: console
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end }}
