apiVersion: v1
kind: Service
metadata:
  name: {{ include "devault.fullname" . }}-api
  labels:
    {{- include "devault.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - name: http
      port: {{ .Values.service.api.httpPort }}
      targetPort: http
    - name: grpc
      port: {{ .Values.service.api.grpcPort }}
      targetPort: grpc
  selector:
    {{- include "devault.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
