"""initial_schema

Revision ID: 9d455b3193d4
Revises: 
Create Date: 2026-05-11 22:39:40.669225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d455b3193d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devault_agent_enrollments',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('allowed_tenant_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('devault_edge_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_release', sa.String(length=64), nullable=True),
    sa.Column('proto_package', sa.String(length=128), nullable=True),
    sa.Column('git_commit', sa.String(length=64), nullable=True),
    sa.Column('last_register_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('host_os', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('agent_env', sa.String(length=128), nullable=True),
    sa.Column('backup_path_allowlist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devault_tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('require_encrypted_artifacts', sa.Boolean(), nullable=False),
    sa.Column('kms_envelope_key_id', sa.String(length=2048), nullable=True),
    sa.Column('s3_bucket', sa.String(length=255), nullable=True),
    sa.Column('s3_assume_role_arn', sa.String(length=2048), nullable=True),
    sa.Column('s3_assume_role_external_id', sa.String(length=1224), nullable=True),
    sa.Column('policy_paths_allowlist_mode', sa.String(length=16), nullable=False),
    sa.Column('require_mfa_for_admins', sa.Boolean(), nullable=False),
    sa.Column('sso_oidc_issuer', sa.Text(), nullable=True),
    sa.Column('sso_oidc_audience', sa.Text(), nullable=True),
    sa.Column('sso_oidc_role_claim', sa.String(length=64), nullable=False),
    sa.Column('sso_oidc_email_claim', sa.String(length=64), nullable=False),
    sa.Column('sso_password_login_disabled', sa.Boolean(), nullable=False),
    sa.Column('sso_jit_provisioning', sa.Boolean(), nullable=False),
    sa.Column('sso_saml_entity_id', sa.Text(), nullable=True),
    sa.Column('sso_saml_acs_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devault_tenants_slug'), 'devault_tenants', ['slug'], unique=True)
    op.create_table('devault_agent_pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['devault_tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devault_agent_pools_tenant_id'), 'devault_agent_pools', ['tenant_id'], unique=False)
    op.create_table('devault_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('plugin', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('restore_artifact_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('lease_agent_id', sa.UUID(), nullable=True),
    sa.Column('lease_agent_hostname', sa.String(length=255), nullable=True),
    sa.Column('completed_agent_hostname', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bundle_wip_multipart_upload_id', sa.String(length=1024), nullable=True),
    sa.Column('bundle_wip_content_length', sa.BigInteger(), nullable=True),
    sa.Column('bundle_wip_part_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('result_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['devault_tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_jobs_tenant_id_idempotency_key')
    )
    op.create_index(op.f('ix_devault_jobs_kind'), 'devault_jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_devault_jobs_status'), 'devault_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_devault_jobs_tenant_id'), 'devault_jobs', ['tenant_id'], unique=False)
    op.create_table('devault_agent_pool_members',
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['devault_agent_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pool_id', 'agent_id')
    )
    op.create_table('devault_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('storage_backend', sa.String(length=16), nullable=False),
    sa.Column('bundle_key', sa.String(length=1024), nullable=False),
    sa.Column('manifest_key', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('compression', sa.String(length=32), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retain_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['devault_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['devault_tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devault_artifacts_job_id'), 'devault_artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_devault_artifacts_tenant_id'), 'devault_artifacts', ['tenant_id'], unique=False)
    op.create_table('devault_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plugin', sa.String(length=32), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bound_agent_id', sa.UUID(), nullable=True),
    sa.Column('bound_agent_pool_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bound_agent_pool_id'], ['devault_agent_pools.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['devault_tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devault_policies_plugin'), 'devault_policies', ['plugin'], unique=False)
    op.create_index(op.f('ix_devault_policies_tenant_id'), 'devault_policies', ['tenant_id'], unique=False)
    op.create_table('devault_restore_drill_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('cron_expression', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('drill_base_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['devault_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['devault_tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devault_restore_drill_schedules_artifact_id'), 'devault_restore_drill_schedules', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_devault_restore_drill_schedules_tenant_id'), 'devault_restore_drill_schedules', ['tenant_id'], unique=False)
    op.create_table('devault_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('cron_expression', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['devault_policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['devault_tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devault_schedules_policy_id'), 'devault_schedules', ['policy_id'], unique=False)
    op.create_index(op.f('ix_devault_schedules_tenant_id'), 'devault_schedules', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devault_schedules_tenant_id'), table_name='devault_schedules')
    op.drop_index(op.f('ix_devault_schedules_policy_id'), table_name='devault_schedules')
    op.drop_table('devault_schedules')
    op.drop_index(op.f('ix_devault_restore_drill_schedules_tenant_id'), table_name='devault_restore_drill_schedules')
    op.drop_index(op.f('ix_devault_restore_drill_schedules_artifact_id'), table_name='devault_restore_drill_schedules')
    op.drop_table('devault_restore_drill_schedules')
    op.drop_index(op.f('ix_devault_policies_tenant_id'), table_name='devault_policies')
    op.drop_index(op.f('ix_devault_policies_plugin'), table_name='devault_policies')
    op.drop_table('devault_policies')
    op.drop_index(op.f('ix_devault_artifacts_tenant_id'), table_name='devault_artifacts')
    op.drop_index(op.f('ix_devault_artifacts_job_id'), table_name='devault_artifacts')
    op.drop_table('devault_artifacts')
    op.drop_table('devault_agent_pool_members')
    op.drop_index(op.f('ix_devault_jobs_tenant_id'), table_name='devault_jobs')
    op.drop_index(op.f('ix_devault_jobs_status'), table_name='devault_jobs')
    op.drop_index(op.f('ix_devault_jobs_kind'), table_name='devault_jobs')
    op.drop_table('devault_jobs')
    op.drop_index(op.f('ix_devault_agent_pools_tenant_id'), table_name='devault_agent_pools')
    op.drop_table('devault_agent_pools')
    op.drop_index(op.f('ix_devault_tenants_slug'), table_name='devault_tenants')
    op.drop_table('devault_tenants')
    op.drop_table('devault_edge_agents')
    op.drop_table('devault_agent_enrollments')
    # ### end Alembic commands ###
