# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import agent_pb2 as agent__pb2


class AgentControlStub(object):
    """Agent control plane: Pull lease + storage grants + completion.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/devault.agent.v1.AgentControl/Heartbeat',
                request_serializer=agent__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=agent__pb2.HeartbeatReply.FromString,
                _registered_method=True)
        self.LeaseJobs = channel.unary_unary(
                '/devault.agent.v1.AgentControl/LeaseJobs',
                request_serializer=agent__pb2.LeaseJobsRequest.SerializeToString,
                response_deserializer=agent__pb2.LeaseJobsReply.FromString,
                _registered_method=True)
        self.RequestStorageGrant = channel.unary_unary(
                '/devault.agent.v1.AgentControl/RequestStorageGrant',
                request_serializer=agent__pb2.RequestStorageGrantRequest.SerializeToString,
                response_deserializer=agent__pb2.RequestStorageGrantReply.FromString,
                _registered_method=True)
        self.ReportProgress = channel.unary_unary(
                '/devault.agent.v1.AgentControl/ReportProgress',
                request_serializer=agent__pb2.ReportProgressRequest.SerializeToString,
                response_deserializer=agent__pb2.ReportProgressReply.FromString,
                _registered_method=True)
        self.CompleteJob = channel.unary_unary(
                '/devault.agent.v1.AgentControl/CompleteJob',
                request_serializer=agent__pb2.CompleteJobRequest.SerializeToString,
                response_deserializer=agent__pb2.CompleteJobReply.FromString,
                _registered_method=True)


class AgentControlServicer(object):
    """Agent control plane: Pull lease + storage grants + completion.

    """

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaseJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestStorageGrant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=agent__pb2.HeartbeatRequest.FromString,
                    response_serializer=agent__pb2.HeartbeatReply.SerializeToString,
            ),
            'LeaseJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaseJobs,
                    request_deserializer=agent__pb2.LeaseJobsRequest.FromString,
                    response_serializer=agent__pb2.LeaseJobsReply.SerializeToString,
            ),
            'RequestStorageGrant': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestStorageGrant,
                    request_deserializer=agent__pb2.RequestStorageGrantRequest.FromString,
                    response_serializer=agent__pb2.RequestStorageGrantReply.SerializeToString,
            ),
            'ReportProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportProgress,
                    request_deserializer=agent__pb2.ReportProgressRequest.FromString,
                    response_serializer=agent__pb2.ReportProgressReply.SerializeToString,
            ),
            'CompleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteJob,
                    request_deserializer=agent__pb2.CompleteJobRequest.FromString,
                    response_serializer=agent__pb2.CompleteJobReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'devault.agent.v1.AgentControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('devault.agent.v1.AgentControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentControl(object):
    """Agent control plane: Pull lease + storage grants + completion.

    """

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devault.agent.v1.AgentControl/Heartbeat',
            agent__pb2.HeartbeatRequest.SerializeToString,
            agent__pb2.HeartbeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaseJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devault.agent.v1.AgentControl/LeaseJobs',
            agent__pb2.LeaseJobsRequest.SerializeToString,
            agent__pb2.LeaseJobsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestStorageGrant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devault.agent.v1.AgentControl/RequestStorageGrant',
            agent__pb2.RequestStorageGrantRequest.SerializeToString,
            agent__pb2.RequestStorageGrantReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devault.agent.v1.AgentControl/ReportProgress',
            agent__pb2.ReportProgressRequest.SerializeToString,
            agent__pb2.ReportProgressReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/devault.agent.v1.AgentControl/CompleteJob',
            agent__pb2.CompleteJobRequest.SerializeToString,
            agent__pb2.CompleteJobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
