/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List edge Agents (fleet inventory) */
        get: operations["list_agents_api_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/enrollment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent tenant enrollment (authorized tenant UUIDs for gRPC) */
        get: operations["get_agent_enrollment_api_v1_agents__agent_id__enrollment_get"];
        /** Set or replace Agent tenant enrollment (admin) */
        put: operations["put_agent_enrollment_api_v1_agents__agent_id__enrollment_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one Agent by id */
        get: operations["get_agent_api_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/revoke-grpc-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Register-minted gRPC bearer tokens for this Agent (Redis)
         * @description Bump session generation so all per-Agent Bearer tokens minted via Register become invalid.
         */
        post: operations["revoke_agent_grpc_sessions_api_v1_agents__agent_id__revoke_grpc_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant-agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents enrolled for the effective tenant (with fleet snapshot when known) */
        get: operations["list_tenant_scoped_agents_api_v1_tenant_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent pools for the effective tenant */
        get: operations["list_agent_pools_api_v1_agent_pools_get"];
        put?: never;
        /** Create an Agent pool (tenant-scoped) */
        post: operations["create_agent_pool_api_v1_agent_pools_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-pools/{pool_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pool with members and last-seen hints */
        get: operations["get_agent_pool_api_v1_agent_pools__pool_id__get"];
        put?: never;
        post?: never;
        /** Delete pool (clears policy bindings that reference it) */
        delete: operations["delete_agent_pool_api_v1_agent_pools__pool_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-pools/{pool_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace pool members (enrollment for tenant required per member) */
        put: operations["put_agent_pool_members_api_v1_agent_pools__pool_id__members_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue backup job */
        post: operations["create_backup_job_api_v1_jobs_backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue restore job */
        post: operations["create_restore_job_api_v1_jobs_restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/path-precheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue backup path precheck job (Agent read-only) */
        post: operations["create_path_precheck_job_api_v1_jobs_path_precheck_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/restore-drill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue automated restore drill job */
        post: operations["create_restore_drill_job_api_v1_jobs_restore_drill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry failed backup job */
        post: operations["retry_job_api_v1_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job by id */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get artifact */
        get: operations["get_artifact_api_v1_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List artifacts */
        get: operations["list_artifacts_api_v1_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/legal-hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set legal hold (admin) */
        patch: operations["patch_artifact_legal_hold_api_v1_artifacts__artifact_id__legal_hold_patch"];
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List policies */
        get: operations["list_policies_api_v1_policies_get"];
        put?: never;
        /** Create policy */
        post: operations["create_policy_api_v1_policies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get policy */
        get: operations["get_policy_api_v1_policies__policy_id__get"];
        put?: never;
        post?: never;
        /** Delete policy */
        delete: operations["delete_policy_api_v1_policies__policy_id__delete"];
        options?: never;
        head?: never;
        /** Update policy */
        patch: operations["patch_policy_api_v1_policies__policy_id__patch"];
        trace?: never;
    };
    "/api/v1/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List schedules */
        get: operations["list_schedules_api_v1_schedules_get"];
        put?: never;
        /** Create schedule */
        post: operations["create_schedule_api_v1_schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules/{schedule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get schedule */
        get: operations["get_schedule_api_v1_schedules__schedule_id__get"];
        put?: never;
        post?: never;
        /** Delete schedule */
        delete: operations["delete_schedule_api_v1_schedules__schedule_id__delete"];
        options?: never;
        head?: never;
        /** Update schedule */
        patch: operations["patch_schedule_api_v1_schedules__schedule_id__patch"];
        trace?: never;
    };
    "/api/v1/restore-drill-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List restore-drill schedules */
        get: operations["list_restore_drill_schedules_api_v1_restore_drill_schedules_get"];
        put?: never;
        /** Create restore-drill cron schedule */
        post: operations["create_restore_drill_schedule_api_v1_restore_drill_schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restore-drill-schedules/{schedule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get restore-drill schedule */
        get: operations["get_restore_drill_schedule_api_v1_restore_drill_schedules__schedule_id__get"];
        put?: never;
        post?: never;
        /** Delete restore-drill schedule */
        delete: operations["delete_restore_drill_schedule_api_v1_restore_drill_schedules__schedule_id__delete"];
        options?: never;
        head?: never;
        /** Update restore-drill schedule */
        patch: operations["patch_restore_drill_schedule_api_v1_restore_drill_schedules__schedule_id__patch"];
        trace?: never;
    };
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenants */
        get: operations["list_tenants_api_v1_tenants_get"];
        put?: never;
        /** Create tenant */
        post: operations["create_tenant_api_v1_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update tenant (admin) */
        patch: operations["patch_tenant_api_v1_tenants__tenant_id__patch"];
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current session principal
         * @description Returns the authenticated principal derived from `Authorization: Bearer` (API key, legacy `DEVAULT_API_TOKEN`, or OIDC JWT when configured). When authentication is disabled (no API keys and no platform token), returns the dev-open admin principal.
         */
        get: operations["get_auth_session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Control plane release (HTTP); pair with Agent ``Heartbeat`` / ``Register`` version fields.
         */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentEnrollmentOut */
        AgentEnrollmentOut: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Allowed Tenant Ids */
            allowed_tenant_ids: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AgentEnrollmentPut
         * @description Replace authorized tenants for an Agent (admin); required before Register can mint a session token.
         */
        AgentEnrollmentPut: {
            /**
             * Allowed Tenant Ids
             * @description Job tenant_id values this Agent may lease and complete over gRPC.
             */
            allowed_tenant_ids: string[];
        };
        /** AgentPoolCreate */
        AgentPoolCreate: {
            /** Name */
            name: string;
        };
        /** AgentPoolDetailOut */
        AgentPoolDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Members */
            members: components["schemas"]["AgentPoolMemberOut"][];
        };
        /** AgentPoolMemberIn */
        AgentPoolMemberIn: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /**
             * Weight
             * @default 100
             */
            weight: number;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** AgentPoolMemberOut */
        AgentPoolMemberOut: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Weight */
            weight: number;
            /** Sort Order */
            sort_order: number;
            /**
             * Last Seen At
             * @description From edge_agents.last_seen_at when the Agent has checked in.
             */
            last_seen_at?: string | null;
        };
        /** AgentPoolMembersPut */
        AgentPoolMembersPut: {
            /** Members */
            members?: components["schemas"]["AgentPoolMemberIn"][];
        };
        /** AgentPoolOut */
        AgentPoolOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ArtifactLegalHoldPatch */
        ArtifactLegalHoldPatch: {
            /**
             * Legal Hold
             * @description When true, retention purge skips this artifact.
             */
            legal_hold: boolean;
        };
        /**
         * ArtifactOut
         * @description Stored backup artifact metadata.
         */
        ArtifactOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Storage Backend */
            storage_backend: string;
            /** Bundle Key */
            bundle_key: string;
            /** Manifest Key */
            manifest_key: string;
            /** Size Bytes */
            size_bytes: number;
            /** Checksum Sha256 */
            checksum_sha256: string;
            /** Compression */
            compression: string;
            /** Encrypted */
            encrypted: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Retain Until */
            retain_until?: string | null;
            /**
             * Legal Hold
             * @default false
             */
            legal_hold: boolean;
        };
        /**
         * AuthSessionOut
         * @description Resolved principal for Bearer (or dev-open when authentication is disabled).
         */
        AuthSessionOut: {
            /**
             * Role
             * @description RBAC role for REST and future Ant Design Pro `access.ts` routing.
             * @enum {string}
             */
            role: "admin" | "operator" | "auditor";
            /**
             * Principal Label
             * @description Stable display / audit label (e.g. api-key name, legacy token, oidc:sub).
             */
            principal_label: string;
            /**
             * Allowed Tenant Ids
             * @description Tenants this principal may use with `X-DeVault-Tenant-Id`; null means all tenants (admin scope).
             */
            allowed_tenant_ids: string[] | null;
        };
        /**
         * CreateBackupJobBody
         * @description Request body to enqueue a backup job.
         */
        CreateBackupJobBody: {
            /**
             * Plugin
             * @description Backup plugin; only `file` is supported.
             * @default file
             * @constant
             */
            plugin: "file";
            /** @description Inline backup config when not referencing a saved policy. */
            config?: components["schemas"]["FileBackupConfigV1"] | null;
            /**
             * Policy Id
             * @description If set, use the saved policy config instead of inline `config`.
             */
            policy_id?: string | null;
            /**
             * Idempotency Key
             * @description Optional key; duplicate requests with the same key return the existing job.
             */
            idempotency_key?: string | null;
        };
        /**
         * CreatePathPrecheckJobBody
         * @description Agent-only job: verify saved file policy backup paths exist and are readable on the leased Agent.
         */
        CreatePathPrecheckJobBody: {
            /**
             * Policy Id
             * Format: uuid
             * @description Tenant policy whose `paths` are checked (no backup upload).
             */
            policy_id: string;
        };
        /**
         * CreateRestoreDrillJobBody
         * @description Manual automated restore drill: extract artifact under drill_base_path/devault-drill-<job_id>/.
         */
        CreateRestoreDrillJobBody: {
            /**
             * Artifact Id
             * Format: uuid
             * @description Artifact to verify by restoring on the Agent.
             */
            artifact_id: string;
            /**
             * Drill Base Path
             * @description Absolute directory prefix on the Agent (each run uses a unique devault-drill-<job_id>/ subfolder).
             */
            drill_base_path: string;
        };
        /**
         * CreateRestoreJobBody
         * @description Request body to enqueue a restore job.
         */
        CreateRestoreJobBody: {
            /**
             * Artifact Id
             * Format: uuid
             * @description Artifact UUID to restore from.
             */
            artifact_id: string;
            /**
             * Target Path
             * @description Absolute directory to extract into (must be allowed on the Agent).
             */
            target_path: string;
            /**
             * Confirm Overwrite Non Empty
             * @description If true, allow restore when the target directory already has files.
             * @default false
             */
            confirm_overwrite_non_empty: boolean;
        };
        /**
         * EdgeAgentOut
         * @description Registered edge Agent (from gRPC Heartbeat / Register).
         */
        EdgeAgentOut: {
            /**
             * Id
             * Format: uuid
             * @description Same as DEVAULT_AGENT_ID / Heartbeat agent_id.
             */
            id: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /**
             * Agent Release
             * @description Last reported SemVer string.
             */
            agent_release?: string | null;
            /**
             * Proto Package
             * @description Last reported protobuf package (e.g. devault.agent.v1).
             */
            proto_package?: string | null;
            /**
             * Git Commit
             * @description Optional Agent build SHA.
             */
            git_commit?: string | null;
            /**
             * Last Register At
             * @description Last successful Register RPC time, if any.
             */
            last_register_at?: string | null;
            /**
             * Meets Min Supported Version
             * @description True when agent_release parses as SemVer >= DEVAULT_GRPC_MIN_SUPPORTED_AGENT_VERSION.
             */
            meets_min_supported_version: boolean;
            /**
             * Proto Matches Control Plane
             * @description True when proto_package is empty or equals the control plane expected package.
             */
            proto_matches_control_plane: boolean;
            /**
             * Allowed Tenant Ids
             * @description From agent_enrollments; omitted when no enrollment row exists yet.
             */
            allowed_tenant_ids?: string[] | null;
            /**
             * Hostname
             * @description Last reported hostname (Heartbeat snapshot v1).
             */
            hostname?: string | null;
            /**
             * Os
             * @description Last reported OS string (untrusted).
             */
            os?: string | null;
            /**
             * Region
             * @description Optional region tag from Agent.
             */
            region?: string | null;
            /**
             * Env
             * @description Optional environment tag from Agent.
             */
            env?: string | null;
            /**
             * Backup Path Allowlist
             * @description Absolute path prefixes this Agent reported as allowed for backups (Heartbeat).
             */
            backup_path_allowlist?: string[] | null;
        };
        /**
         * EnqueueResponse
         * @description Returned after enqueueing a backup or restore job.
         */
        EnqueueResponse: {
            /**
             * Job Id
             * Format: uuid
             * @description New or existing job id.
             */
            job_id: string;
            /**
             * Status
             * @description Job status at enqueue time (often `pending`).
             */
            status: string;
        };
        /**
         * FileBackupConfigV1
         * @description File-plugin backup configuration (version 1).
         */
        FileBackupConfigV1: {
            /**
             * Version
             * @description Config schema version; must be 1.
             * @default 1
             * @constant
             */
            version: 1;
            /**
             * Paths
             * @description Absolute paths to back up (files or directories).
             */
            paths: string[];
            /**
             * Excludes
             * @description Optional gitwildmatch patterns to exclude.
             */
            excludes?: string[];
            /**
             * Follow Symlinks
             * @description Follow symlinks when walking paths (reserved).
             * @default false
             */
            follow_symlinks: boolean;
            /**
             * Preserve Uid Gid
             * @description Preserve uid/gid in archive metadata (reserved).
             * @default true
             */
            preserve_uid_gid: boolean;
            /**
             * One Filesystem
             * @description Stay on one filesystem (reserved).
             * @default false
             */
            one_filesystem: boolean;
            /**
             * Encrypt Artifacts
             * @description Encrypt backup bundle with AES-256-GCM before upload (KMS envelope or static key).
             * @default false
             */
            encrypt_artifacts: boolean;
            /**
             * Kms Envelope Key Id
             * @description KMS CMK id or ARN for envelope encryption (optional if tenant/platform default is set).
             */
            kms_envelope_key_id?: string | null;
            /**
             * Object Lock Mode
             * @description S3 Object Lock mode when the bucket has Object Lock enabled.
             */
            object_lock_mode?: ("GOVERNANCE" | "COMPLIANCE") | null;
            /**
             * Object Lock Retain Days
             * @description Object Lock retention window in days from upload time.
             */
            object_lock_retain_days?: number | null;
            /**
             * Retention Days
             * @description Optional retention: artifact eligible for automatic deletion this many days after successful backup.
             */
            retention_days?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "backup" | "restore" | "restore_drill" | "path_precheck";
        /**
         * JobOut
         * @description Job row returned by the API.
         */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Kind */
            kind: string;
            /** Plugin */
            plugin: string;
            /** Status */
            status: string;
            /** Trigger */
            trigger: string;
            /** Policy Id */
            policy_id?: string | null;
            /** Config Snapshot */
            config_snapshot: {
                [key: string]: unknown;
            };
            /** Restore Artifact Id */
            restore_artifact_id: string | null;
            /** Lease Agent Id */
            lease_agent_id?: string | null;
            /**
             * Lease Agent Hostname
             * @description Hostname snapshot from edge_agents at LeaseJobs time (audit).
             */
            lease_agent_hostname?: string | null;
            /**
             * Completed Agent Hostname
             * @description Hostname from CompleteJob.agent_hostname or edge_agents at completion (audit).
             */
            completed_agent_hostname?: string | null;
            /** Lease Expires At */
            lease_expires_at?: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Trace Id */
            trace_id: string | null;
            /**
             * Result Meta
             * @description restore_drill / path_precheck: structured report from the Agent (see `schema` in JSON).
             */
            result_meta?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "uploading" | "verifying" | "success" | "failed" | "retrying" | "cancelled";
        /** PolicyCreate */
        PolicyCreate: {
            /**
             * Name
             * @description Human-readable policy name.
             */
            name: string;
            /**
             * Plugin
             * @description Plugin; only `file` is supported.
             * @default file
             * @constant
             */
            plugin: "file";
            /** @description Paths and exclude patterns. */
            config: components["schemas"]["FileBackupConfigV1"];
            /**
             * Enabled
             * @description Whether schedules and manual runs may use this policy.
             * @default true
             */
            enabled: boolean;
            /**
             * Bound Agent Id
             * @description If set, only this Agent may LeaseJobs for backups of this policy.
             */
            bound_agent_id?: string | null;
            /**
             * Bound Agent Pool Id
             * @description If set, only Agents in this pool may lease; mutually exclusive with bound_agent_id.
             */
            bound_agent_pool_id?: string | null;
        };
        /** PolicyOut */
        PolicyOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Name */
            name: string;
            /** Plugin */
            plugin: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
            /** Bound Agent Id */
            bound_agent_id?: string | null;
            /** Bound Agent Pool Id */
            bound_agent_pool_id?: string | null;
        };
        /** PolicyPatch */
        PolicyPatch: {
            /** Name */
            name?: string | null;
            config?: components["schemas"]["FileBackupConfigV1"] | null;
            /** Enabled */
            enabled?: boolean | null;
            /**
             * Bound Agent Id
             * @description Set/clear execution binding.
             */
            bound_agent_id?: string | null;
            /**
             * Bound Agent Pool Id
             * @description Set/clear pool binding.
             */
            bound_agent_pool_id?: string | null;
        };
        /** RestoreDrillScheduleCreate */
        RestoreDrillScheduleCreate: {
            /**
             * Artifact Id
             * Format: uuid
             * @description Artifact whose recoverability is verified each run.
             */
            artifact_id: string;
            /**
             * Cron Expression
             * @description Five-field cron for devault-scheduler (same as backup schedules).
             */
            cron_expression: string;
            /**
             * Timezone
             * @description IANA time zone name.
             * @default UTC
             */
            timezone: string;
            /**
             * Enabled
             * @description Whether the scheduler should enqueue drills.
             * @default true
             */
            enabled: boolean;
            /**
             * Drill Base Path
             * @description Absolute path prefix on the Agent (runs extract into devault-drill-<job_id>/ below this path).
             */
            drill_base_path: string;
        };
        /** RestoreDrillScheduleOut */
        RestoreDrillScheduleOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Artifact Id
             * Format: uuid
             */
            artifact_id: string;
            /** Cron Expression */
            cron_expression: string;
            /** Timezone */
            timezone: string;
            /** Enabled */
            enabled: boolean;
            /** Drill Base Path */
            drill_base_path: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RestoreDrillSchedulePatch */
        RestoreDrillSchedulePatch: {
            /** Cron Expression */
            cron_expression?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Drill Base Path */
            drill_base_path?: string | null;
            /** Artifact Id */
            artifact_id?: string | null;
        };
        /** ScheduleCreate */
        ScheduleCreate: {
            /**
             * Policy Id
             * Format: uuid
             * @description Policy to run on this cron.
             */
            policy_id: string;
            /**
             * Cron Expression
             * @description Five-field cron expression (APScheduler / croniter).
             */
            cron_expression: string;
            /**
             * Timezone
             * @description IANA time zone name for the cron.
             * @default UTC
             */
            timezone: string;
            /**
             * Enabled
             * @description Whether the scheduler should fire this schedule.
             * @default true
             */
            enabled: boolean;
        };
        /** ScheduleOut */
        ScheduleOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Policy Id
             * Format: uuid
             */
            policy_id: string;
            /** Cron Expression */
            cron_expression: string;
            /** Timezone */
            timezone: string;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SchedulePatch */
        SchedulePatch: {
            /** Cron Expression */
            cron_expression?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** TenantCreate */
        TenantCreate: {
            /** Name */
            name: string;
            /**
             * Slug
             * @description Lowercase URL-safe identifier (e.g. acme-corp).
             */
            slug: string;
        };
        /** TenantOut */
        TenantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Require Encrypted Artifacts
             * @default false
             */
            require_encrypted_artifacts: boolean;
            /** Kms Envelope Key Id */
            kms_envelope_key_id?: string | null;
            /** S3 Bucket */
            s3_bucket?: string | null;
            /** S3 Assume Role Arn */
            s3_assume_role_arn?: string | null;
            /** S3 Assume Role External Id */
            s3_assume_role_external_id?: string | null;
            /**
             * Policy Paths Allowlist Mode
             * @description When enforce/warn: file policy paths must fall under enrolled Agents' Heartbeat-reported backup_path_allowlist union (empty union skips validation).
             * @default off
             * @enum {string}
             */
            policy_paths_allowlist_mode: "off" | "enforce" | "warn";
        };
        /** TenantPatch */
        TenantPatch: {
            /** Name */
            name?: string | null;
            /** Require Encrypted Artifacts */
            require_encrypted_artifacts?: boolean | null;
            /** Kms Envelope Key Id */
            kms_envelope_key_id?: string | null;
            /** S3 Bucket */
            s3_bucket?: string | null;
            /** S3 Assume Role Arn */
            s3_assume_role_arn?: string | null;
            /** S3 Assume Role External Id */
            s3_assume_role_external_id?: string | null;
            /** Policy Paths Allowlist Mode */
            policy_paths_allowlist_mode?: ("off" | "enforce" | "warn") | null;
        };
        /**
         * TenantScopedAgentOut
         * @description Agent enrolled for the requested tenant, with optional fleet snapshot from ``edge_agents``.
         */
        TenantScopedAgentOut: {
            /**
             * Id
             * Format: uuid
             * @description Agent UUID (same as DEVAULT_AGENT_ID).
             */
            id: string;
            /**
             * Allowed Tenant Ids
             * @description Full enrollment list for this Agent (includes the effective tenant).
             */
            allowed_tenant_ids: string[];
            /**
             * First Seen At
             * @description Set once the Agent has checked in over gRPC.
             */
            first_seen_at?: string | null;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Agent Release */
            agent_release?: string | null;
            /** Proto Package */
            proto_package?: string | null;
            /** Git Commit */
            git_commit?: string | null;
            /** Last Register At */
            last_register_at?: string | null;
            /**
             * Meets Min Supported Version
             * @description False when unknown or below DEVAULT_GRPC_MIN_SUPPORTED_AGENT_VERSION.
             * @default false
             */
            meets_min_supported_version: boolean;
            /**
             * Proto Matches Control Plane
             * @description True when proto unknown or matches control plane package.
             * @default true
             */
            proto_matches_control_plane: boolean;
            /** Hostname */
            hostname?: string | null;
            /** Os */
            os?: string | null;
            /** Region */
            region?: string | null;
            /** Env */
            env?: string | null;
            /** Backup Path Allowlist */
            backup_path_allowlist?: string[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agents_api_v1_agents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeAgentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_enrollment_api_v1_agents__agent_id__enrollment_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentEnrollmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_agent_enrollment_api_v1_agents__agent_id__enrollment_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentEnrollmentPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentEnrollmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_api_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeAgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_agent_grpc_sessions_api_v1_agents__agent_id__revoke_grpc_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tenant_scoped_agents_api_v1_tenant_agents_get: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantScopedAgentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_pools_api_v1_agent_pools_get: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPoolOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_pool_api_v1_agent_pools_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentPoolCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPoolOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_pool_api_v1_agent_pools__pool_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                pool_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPoolDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_pool_api_v1_agent_pools__pool_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                pool_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_agent_pool_members_api_v1_agent_pools__pool_id__members_put: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                pool_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentPoolMembersPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPoolDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_backup_job_api_v1_jobs_backup_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBackupJobBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_restore_job_api_v1_jobs_restore_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRestoreJobBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_path_precheck_job_api_v1_jobs_path_precheck_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePathPrecheckJobBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_restore_drill_job_api_v1_jobs_restore_drill_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRestoreDrillJobBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_v1_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filter by job kind */
                kind?: components["schemas"]["JobKind"] | null;
                /** @description Filter by job status */
                status?: components["schemas"]["JobStatus"] | null;
            };
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_v1_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_artifacts_api_v1_artifacts_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_artifact_legal_hold_api_v1_artifacts__artifact_id__legal_hold_patch: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactLegalHoldPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policies_api_v1_policies_get: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_policy_api_v1_policies_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_policy_api_v1_policies__policy_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_policy_api_v1_policies__policy_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_policy_api_v1_policies__policy_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_schedules_api_v1_schedules_get: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_schedule_api_v1_schedules_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_api_v1_schedules__schedule_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_schedule_api_v1_schedules__schedule_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_schedule_api_v1_schedules__schedule_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchedulePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_restore_drill_schedules_api_v1_restore_drill_schedules_get: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreDrillScheduleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_restore_drill_schedule_api_v1_restore_drill_schedules_post: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreDrillScheduleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreDrillScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_restore_drill_schedule_api_v1_restore_drill_schedules__schedule_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreDrillScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_restore_drill_schedule_api_v1_restore_drill_schedules__schedule_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_restore_drill_schedule_api_v1_restore_drill_schedules__schedule_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-DeVault-Tenant-Id"?: string | null;
                authorization?: string | null;
            };
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreDrillSchedulePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreDrillScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tenants_api_v1_tenants_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tenant_api_v1_tenants_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_tenant_api_v1_tenants__tenant_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auth_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
